import { CHUNK_SIZE, UNIT_SIZE } from "../../../common/constants/constants";
import { march } from "../compute";
import { MarchingCubesMesh } from "../mesh";
import { MarchingCubesResult } from "../types/MarchingCubesResult";
import { ScalarField } from "../utils/scalarField";
import { FillFunction } from "../types/FillFunction";
import { ChunkCoord } from "../types/ChunkCoord";
import { RaycastHit, TriangleSpatialHash } from "../utils/collider";

// Bump this string whenever terrain generation parameters change (scale,
// octaves, isolevel, etc.) to invalidate stale sessionStorage caches.
const CACHE_VERSION = 'v2.0';

// WHY: process in 32 KB slices so String.fromCharCode.apply() never exceeds
// the JS engine's maximum argument count (varies by runtime, ~65 K args).
const B64_STEP = 0x8000;

function float32ToBase64(arr: Float32Array): string {
    const bytes = new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength);
    let binary = '';
    for (let i = 0; i < bytes.length; i += B64_STEP) {
        // eslint-disable-next-line prefer-spread
        binary += String.fromCharCode.apply(null, bytes.subarray(i, i + B64_STEP) as unknown as number[]);
    }
    return btoa(binary);
}

function base64ToFloat32(b64: string): Float32Array {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return new Float32Array(bytes.buffer);
}

export class Chunk {
    readonly worldOffset: [number, number, number];

    private mesh: MarchingCubesMesh;
    private result: MarchingCubesResult;
    // WHY: the spatial hash is built once from the CPU-side vertex data that
    // march() already produces. It partitions triangles into a uniform grid so
    // collision queries only test a small local subset rather than the full mesh.
    private collider: TriangleSpatialHash;

    // WHY: these fields are needed for lazy field reconstruction and sculpting.
    // The scalar field is kept alive after march() so sculptAt() can modify
    // individual corners without rebuilding the full field from scratch. For
    // chunks loaded from sessionStorage cache, the field starts null and is
    // regenerated from fillFn on the first sculpt operation.
    private field: ScalarField | null;
    private readonly fillFn: FillFunction;
    private readonly isolevel: number;
    private readonly cx: number;
    private readonly cy: number;
    private readonly cz: number;
    private readonly cacheKey: string;

    constructor(
        gl: WebGL2RenderingContext,
        coord: ChunkCoord,
        fillFn: FillFunction,
        isolevel: number,
    ) {
        const { cx, cy, cz } = coord;

        this.fillFn = fillFn;
        this.isolevel = isolevel;
        this.cx = cx;
        this.cy = cy;
        this.cz = cz;

        this.worldOffset = [
            cx * CHUNK_SIZE * UNIT_SIZE,
            cy * CHUNK_SIZE * UNIT_SIZE,
            cz * CHUNK_SIZE * UNIT_SIZE,
        ];

        // --- Session-storage cache lookup -----------------------------------
        // WHY: marching cubes for a 64³ chunk is CPU-heavy (scalar field eval +
        // mesh extraction). Caching the vertex buffer in sessionStorage lets
        // subsequent page reloads within the same browser tab skip the work
        // entirely.  Cache misses (first load, or after CACHE_VERSION bump)
        // fall through to the normal march() path and then persist the result.
        // Quota-exceeded and disabled-storage errors are caught and ignored so
        // the game still works without caching.
        this.cacheKey = `mc_${CACHE_VERSION}_${cx}_${cy}_${cz}`;
        let cached: MarchingCubesResult | null = null;
        try {
            const stored = sessionStorage.getItem(this.cacheKey);
            if (stored !== null) {
                const vertices = base64ToFloat32(stored);
                cached = { vertices, vertexCount: vertices.length / 3 };
            }
        } catch { /* storage unavailable — proceed without cache */ }

        if (cached) {
            this.result = cached;
            // WHY: cache stores only vertex data, not the scalar field. The
            // field is null here and will be lazily regenerated by sculptAt()
            // on first user interaction if this chunk is sculpted.
            this.field = null;
        } else {
            // WHY: ScalarField is (CHUNK_SIZE + 1) on each axis so the last column
            // of voxels is shared with the neighbour chunk, preventing seam cracks.
            const field = new ScalarField(CHUNK_SIZE + 1);

            // Fill using world-space voxel coordinates so a global noise/SDF
            // function is continuous across chunk boundaries.
            field.fill((lx, ly, lz) =>
                fillFn(
                    cx * CHUNK_SIZE + lx,
                    cy * CHUNK_SIZE + ly,
                    cz * CHUNK_SIZE + lz,
                )
            );

            this.result = march(field, isolevel);
            // WHY: keep the field alive — sculptAt() reads and modifies it
            // in-place so we never need to re-evaluate the fill function again
            // for this chunk after the first frame.
            this.field = field;

            try {
                sessionStorage.setItem(this.cacheKey, float32ToBase64(this.result.vertices));
            } catch { /* quota exceeded — operate without cache */ }
        }
        // --------------------------------------------------------------------

        this.mesh = new MarchingCubesMesh(gl, this.result);
        this.collider = new TriangleSpatialHash(this.result, this.worldOffset);
    }

    /**
     * Returns true if the given world-space AABB overlaps any triangle in this
     * chunk's mesh. Used by the camera controller for solid-geometry collision.
     */
    collidesWithAABB(
        minX: number, minY: number, minZ: number,
        maxX: number, maxY: number, maxZ: number,
    ): boolean {
        return this.collider.collidesWithAABB(minX, minY, minZ, maxX, maxY, maxZ);
    }

    /** Cast a ray and return the nearest hit triangle in this chunk, or null. */
    raycastTriangle(
        ox: number, oy: number, oz: number,
        dx: number, dy: number, dz: number,
        maxDist: number,
    ): RaycastHit | null {
        return this.collider.raycastTriangle(ox, oy, oz, dx, dy, dz, maxDist);
    }

    /**
     * Bind the mesh and draw. The caller is responsible for setting
     * u_chunkOffset before calling this.
     */
    draw(attributeLocation: number): void {
        this.mesh.bind(attributeLocation);
        this.mesh.draw();
    }

    /**
     * Re-run marching cubes with a new fill function (e.g. for dynamic terrain).
     * Uploads updated vertex data via gl.DYNAMIC_DRAW via mesh.update().
     */
    rebuild(fillFn: FillFunction, isolevel: number): void {
        const field = new ScalarField(CHUNK_SIZE + 1);
        field.fill(fillFn);
        this.result = march(field, isolevel);
        this.mesh.update(this.result);
        this.collider = new TriangleSpatialHash(this.result, this.worldOffset);
    }

    /**
     * Modify the scalar field within a sphere of the given world-space radius
     * centred on (wx, wy, wz), then rebuild the mesh.
     *
     * Positive delta adds material (fills), negative delta removes it.
     * The influence falls off linearly from |delta| at the centre to 0 at
     * the edge of the sphere so edits feel smooth rather than blocky.
     *
     * WHY lazy field init: chunks loaded from sessionStorage cache have only
     * vertex data, not the scalar field. On the first sculpt we regenerate
     * the field by re-evaluating the original fill function, which is O(n³)
     * but happens at most once per cached chunk per session.
     */
    sculptAt(wx: number, wy: number, wz: number, radius: number, delta: number): void {
        if (!this.field) {
            this.field = new ScalarField(CHUNK_SIZE + 1);
            this.field.fill((lx, ly, lz) =>
                this.fillFn(
                    this.cx * CHUNK_SIZE + lx,
                    this.cy * CHUNK_SIZE + ly,
                    this.cz * CHUNK_SIZE + lz,
                )
            );
        }

        const [offX, offY, offZ] = this.worldOffset;

        // WHY: convert world-space hit centre to field-grid coordinates.
        // Each grid step equals UNIT_SIZE world units, so dividing by UNIT_SIZE
        // maps world position to a (possibly fractional) grid index.
        const localX = (wx - offX) / UNIT_SIZE;
        const localY = (wy - offY) / UNIT_SIZE;
        const localZ = (wz - offZ) / UNIT_SIZE;
        const r = radius / UNIT_SIZE;
        const r2 = r * r;

        const x0 = Math.max(0, Math.floor(localX - r));
        const x1 = Math.min(this.field.width - 1, Math.ceil(localX + r));
        const y0 = Math.max(0, Math.floor(localY - r));
        const y1 = Math.min(this.field.height - 1, Math.ceil(localY + r));
        const z0 = Math.max(0, Math.floor(localZ - r));
        const z1 = Math.min(this.field.depth - 1, Math.ceil(localZ + r));

        let modified = false;
        for (let fz = z0; fz <= z1; fz++) {
            for (let fy = y0; fy <= y1; fy++) {
                for (let fx = x0; fx <= x1; fx++) {
                    const ex = fx - localX, ey = fy - localY, ez = fz - localZ;
                    const dist2 = ex * ex + ey * ey + ez * ez;
                    if (dist2 > r2) continue;
                    // WHY linear falloff: a flat-top brush creates sharp rings
                    // at the brush boundary. Linear falloff blends naturally
                    // with neighbouring unmodified corners.
                    const falloff = 1.0 - Math.sqrt(dist2) / r;
                    this.field.data[this.field.index(fx, fy, fz)] += delta * falloff;
                    modified = true;
                }
            }
        }

        if (!modified) return;

        this.result = march(this.field, this.isolevel);
        this.mesh.update(this.result);
        this.collider = new TriangleSpatialHash(this.result, this.worldOffset);

        // WHY: the vertex data no longer matches the cached entry. Remove it
        // so the next page load regenerates from the modified field rather
        // than restoring the pre-sculpt geometry.
        try { sessionStorage.removeItem(this.cacheKey); } catch { /* ignore */ }
    }

    destroy(): void {
        this.mesh.destroy();
    }
}