export const GL_LIMITS = {
    MAX_CUBE_MAP_TEXTURE_SIZE: 4096,
    MAX_RENDERBUFFER_SIZE: 4096,
    MAX_TEXTURE_SIZE: 4096,
    MAX_VIEWPORT_DIMS: [4096, 4096] as [number, number],
    MAX_VERTEX_TEXTURE_IMAGE_UNITS: 4,
    MAX_TEXTURE_IMAGE_UNITS: 8,
    MAX_COMBINED_TEXTURE_IMAGE_UNITS: 8,
    MAX_VERTEX_ATTRIBS: 16,
    MAX_VARYING_VECTORS: 8,
    MAX_VERTEX_UNIFORM_VECTORS: 128,
    MAX_FRAGMENT_UNIFORM_VECTORS: 64,
    ALIASED_POINT_SIZE_RANGE: [1, 100] as [number, number],
} as const;

export type GLLimits = typeof GL_LIMITS;